# -*- coding: utf-8 -*-
"""project3canda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Twp_TBIyCaRbCJLl3BmYEQScQqrYUDst

Predict Canada’s per capita income in year 2020. There is an exercise folder here on github at same level as this notebook, download that and you will find canada_per_capita_income.csv file. Using this build a regression model and predict the per capita income fo canadian citizens in year 2020.
"""


import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# --------------------------------------------------
# Page Config
# --------------------------------------------------
st.set_page_config(
    page_title="Canada Per Capita Income Prediction",
    page_icon="📈",
    layout="wide"
)

st.title("📈 Canada Per Capita Income Prediction")
st.write("Predict Canada's per capita income using Linear Regression.")

# --------------------------------------------------
# Load Dataset
# --------------------------------------------------
df = pd.read_csv("canada_per_capita_income.csv")

st.subheader("Dataset")
st.dataframe(df)

# --------------------------------------------------
# Data
# --------------------------------------------------
X = df[['year']]
y = df['per capita income (US$)']

# --------------------------------------------------
# Train Model
# --------------------------------------------------
model = LinearRegression()
model.fit(X, y)

pred_train = model.predict(X)
score = r2_score(y, pred_train)

# --------------------------------------------------
# Sidebar
# --------------------------------------------------
st.sidebar.header("Prediction")

year = st.sidebar.number_input(
    "Enter Year",
    min_value=1960,
    max_value=2100,
    value=2020
)

# --------------------------------------------------
# Prediction
# --------------------------------------------------
prediction = model.predict([[year]])[0]

st.subheader("Prediction")

st.success(
    f"Estimated Per Capita Income in {year} = **${prediction:,.2f}**"
)

# --------------------------------------------------
# Model Details
# --------------------------------------------------
st.subheader("Model Details")

col1, col2 = st.columns(2)

with col1:
    st.metric("Slope", f"{model.coef_[0]:.2f}")

with col2:
    st.metric("R² Score", f"{score:.4f}")

# --------------------------------------------------
# Scatter Plot
# --------------------------------------------------
st.subheader("Dataset Visualization")

fig, ax = plt.subplots(figsize=(8,5))

ax.scatter(
    df["year"],
    df["per capita income (US$)"],
    color="blue",
    label="Actual Data"
)

ax.plot(
    df["year"],
    pred_train,
    color="red",
    linewidth=2,
    label="Regression Line"
)

ax.set_xlabel("Year")
ax.set_ylabel("Per Capita Income (US$)")
ax.legend()

st.pyplot(fig)

# --------------------------------------------------
# Future Prediction Graph
# --------------------------------------------------
st.subheader("Future Prediction")

future_years = np.arange(df["year"].min(), 2035).reshape(-1,1)
future_income = model.predict(future_years)

fig2, ax2 = plt.subplots(figsize=(8,5))

ax2.plot(
    future_years,
    future_income,
    color="green",
    linewidth=2
)

ax2.scatter(year, prediction, color="red", s=100)

ax2.set_xlabel("Year")
ax2.set_ylabel("Predicted Income")

st.pyplot(fig2)

# --------------------------------------------------
# Download Result
# --------------------------------------------------
result = pd.DataFrame({
    "Year":[year],
    "Predicted Income":[prediction]
})

csv = result.to_csv(index=False)

st.download_button(
    "📥 Download Prediction",
    csv,
    file_name="prediction.csv",
    mime="text/csv"
)

# --------------------------------------------------
# Footer
# --------------------------------------------------
st.markdown("---")
st.caption("Developed using Streamlit & Scikit-Learn")
